name: Python CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: install
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        
    - name: install
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
        
    - name: black
      run: |
        black --check .
        
    - name: mypy
      run: |
        mypy ariautils
        mypy tests
        
    - name: Run tests with pytest
      run: |
        pytest
